spring:
    datasource:
        url:  jdbc:mysql://127.0.0.1:3306/personal_database
        username: root
        password: anywhere
        driver-class-name:  com.mysql.jdbc.Driver

ignoreFields: id,is_deleted,create_time,last_update_time