spring:
    datasource:
        url:  jdbc:mysql://127.0.0.1:3306/personal_database
        username: root
        password: anywhere
        driver-class-name:  com.mysql.jdbc.Driver

local:
  databaseName: qq_data
  enums:
    - is_auto_comment,4,5
    - from_new,7,8

ignoreFields: id,is_deleted,create_time,last_update_time

